export interface BTHomeData {
  varName: VarName;
  value: number | string;
  extension?: Unit;
}

export interface BTHomePacket {
  version: string;
  data: BTHomeData[];
}

export interface BtHomeBytesType {
  byteId: number;
  byteLength: number;
  varName: VarName;
  factor: number;
  dataType: DataType;
  unit?: Unit;
  fixedPoint?: number; // allowed number after the decimal eg: 21.1
}

export enum BTHomeVersion {
  v1 = "v1",
  v2 = "v2",
}

export enum VarName {
  acceleration = "acceleration",
  battery = "battery",
  channel = "channel",
  co2ppm = "CO2ppm",
  conductivity = "conductivity",
  count = "count",
  current = "current",
  dewpoint = "dewpoint",
  distanceMM = "distanceMM",
  distanceM = "distanceM",
  duration = "duration",
  energyInkWh = "energyInkWh",
  gas = "gas",
  gyroscope = "gyroscope",
  relativeHumidity = "relativeHumidity",
  illuminance = "illuminance",
  macAddress = "macAddress",
  massKG = "massKG",
  massLB = "massLB",
  moisture = "moisture",
  packetId = "packetId",
  particulateMatter = "particulateMatter",
  pm10 = "pm10",
  power = "power",
  pressure = "pressure",
  raw = "raw",
  rotation = "rotation",
  speed = "speed",
  temperatureC = "temperatureC",
  text = "text",
  timeStamp = "timeStamp",
  tvoc = "tvoc",
  voltage = "voltage",
  volume = "volume",
  volumeML = "volumeML",
  volumeStorage = "volumeStorage",
  volumeFlowRate = "volumeFlowRate",
  uvIndex = "uvIndex",
  water = "water",
  direction = "direction",
  precipitation = "precipitation",
}

export enum DataType {
  uint = "uint",
  sint = "sint",
}

export enum Unit {
  acceleration = "m/s²",
  battery = "%",
  channel = "",
  co2ppm = "ppm",
  conductivity = "	µS/cm",
  count = "",
  current = "A",
  dewpoint = "°C",
  distanceMM = "mm",
  distanceM = "m",
  duration = "s",
  energyInkWh = "kWh",
  gas = "m3",
  gyroscope = "°/s",
  relativeHumidity = "%",
  illuminance = "lux",
  macAddress = "",
  massKG = "kg",
  massLB = "lb",
  moisture = "%",
  packetId = "",
  particulateMatter = "ug/m3",
  pm10 = "ug/m3",
  power = "W",
  pressure = "hPa",
  raw = "",
  rotation = "°",
  speed = "m/s",
  temperatureC = "°C",
  text = "",
  timeStamp = "",
  tvoc = "ug/m3",
  voltage = "V",
  volume = "L",
  volumeML = "mL",
  volumeStorage = "L",
  volumeFlowRate = "m3/hr",
  uvIndex = "",
  water = "L",
  direction = "°",
  precipitation = "",
}

export const btHomeBytes: BtHomeBytesType[] = [
  {
    byteId: 0x51,
    byteLength: 2,
    varName: VarName.acceleration,
    factor: 0.001,
    dataType: DataType.uint,
    unit: Unit.acceleration,
  },

  {
    byteId: 0x01,
    byteLength: 1,
    varName: VarName.battery,
    factor: 1,
    dataType: DataType.uint,
    unit: Unit.battery,
  },

  {
    byteId: 0x60,
    byteLength: 1,
    varName: VarName.channel,
    factor: 1,
    dataType: DataType.uint,
    unit: Unit.channel,
  },

  {
    byteId: 0x12,
    byteLength: 2,
    varName: VarName.co2ppm,
    factor: 1,
    dataType: DataType.uint,
    unit: Unit.co2ppm,
  },

  {
    byteId: 0x56,
    byteLength: 2,
    varName: VarName.conductivity,
    factor: 1,
    dataType: DataType.uint,
    unit: Unit.conductivity,
  },

  {
    byteId: 0x09,
    byteLength: 1,
    varName: VarName.count,
    factor: 1,
    dataType: DataType.uint,
    unit: Unit.count,
  },
  {
    byteId: 0x3d,
    byteLength: 2,
    varName: VarName.count,
    factor: 1,
    dataType: DataType.uint,
    unit: Unit.count,
  },
  {
    byteId: 0x3e,
    byteLength: 4,
    varName: VarName.count,
    factor: 1,
    dataType: DataType.uint,
    unit: Unit.count,
  },
  {
    byteId: 0x59,
    byteLength: 1,
    varName: VarName.count,
    factor: 1,
    dataType: DataType.sint,
    unit: Unit.count,
  },
  {
    byteId: 0x5a,
    byteLength: 2,
    varName: VarName.count,
    factor: 1,
    dataType: DataType.sint,
    unit: Unit.count,
  },
  {
    byteId: 0x5b,
    byteLength: 4,
    varName: VarName.count,
    factor: 1,
    dataType: DataType.sint,
    unit: Unit.count,
  },
  {
    byteId: 0x43,
    byteLength: 2,
    varName: VarName.current,
    factor: 0.001,
    dataType: DataType.uint,
    unit: Unit.current,
  },
  {
    byteId: 0x5d,
    byteLength: 2,
    varName: VarName.current,
    factor: 0.001,
    dataType: DataType.sint,
    unit: Unit.current,
  },
  {
    byteId: 0x08,
    byteLength: 2,
    varName: VarName.dewpoint,
    factor: 0.01,
    dataType: DataType.sint,
    unit: Unit.dewpoint,
  },
  {
    byteId: 0x40,
    byteLength: 2,
    varName: VarName.distanceMM,
    factor: 1,
    dataType: DataType.uint,
    unit: Unit.distanceMM,
  },

  {
    byteId: 0x41,
    byteLength: 2,
    varName: VarName.distanceM,
    factor: 0.1,
    dataType: DataType.uint,
    unit: Unit.distanceM,
  },
  {
    byteId: 0x42,
    byteLength: 3,
    varName: VarName.duration,
    factor: 0.001,
    dataType: DataType.uint,
    unit: Unit.duration,
  },
  {
    byteId: 0x4d,
    byteLength: 4,
    varName: VarName.energyInkWh,
    factor: 0.001,
    dataType: DataType.uint,
    unit: Unit.energyInkWh,
  },
  {
    byteId: 0x0a,
    byteLength: 3,
    varName: VarName.energyInkWh,
    factor: 0.001,
    dataType: DataType.uint,
    unit: Unit.energyInkWh,
    fixedPoint: 3,
  },
  {
    byteId: 0x4b,
    byteLength: 3,
    varName: VarName.gas,
    factor: 0.001,
    dataType: DataType.uint,
    unit: Unit.gas,
  },
  {
    byteId: 0x4c,
    byteLength: 4,
    varName: VarName.gas,
    factor: 0.001,
    dataType: DataType.uint,
    unit: Unit.gas,
  },
  {
    byteId: 0x52,
    byteLength: 2,
    varName: VarName.gyroscope,
    factor: 0.001,
    dataType: DataType.uint,
    unit: Unit.gyroscope,
  },
  {
    byteId: 0x03,
    byteLength: 2,
    varName: VarName.relativeHumidity,
    factor: 0.01,
    dataType: DataType.uint,
    unit: Unit.relativeHumidity,
    fixedPoint: 2,
  },

  {
    byteId: 0x2e,
    byteLength: 1,
    varName: VarName.relativeHumidity,
    factor: 1,
    dataType: DataType.uint,
    unit: Unit.relativeHumidity,
  },

  {
    byteId: 0x05,
    byteLength: 3,
    varName: VarName.illuminance,
    factor: 0.01,
    dataType: DataType.uint,
    unit: Unit.illuminance,
  },

  {
    byteId: 0x06,
    byteLength: 2,
    varName: VarName.massKG,
    factor: 0.01,
    dataType: DataType.uint,
    unit: Unit.massKG,
  },
  {
    byteId: 0x07,
    byteLength: 2,
    varName: VarName.massLB,
    factor: 0.01,
    dataType: DataType.uint,
    unit: Unit.illuminance,
  },
  {
    byteId: 0x14,
    byteLength: 2,
    varName: VarName.moisture,
    factor: 0.01,
    dataType: DataType.uint,
    unit: Unit.moisture,
  },
  {
    byteId: 0x2f,
    byteLength: 1,
    varName: VarName.moisture,
    factor: 1,
    dataType: DataType.uint,
    unit: Unit.moisture,
  },
  {
    byteId: 0x0d,
    byteLength: 2,
    varName: VarName.particulateMatter,
    factor: 1,
    dataType: DataType.uint,
    unit: Unit.particulateMatter,
  },
  {
    byteId: 0x0e,
    byteLength: 2,
    varName: VarName.pm10,
    factor: 1,
    dataType: DataType.uint,
    unit: Unit.pm10,
  },
  {
    byteId: 0x00,
    byteLength: 1,
    varName: VarName.packetId,
    factor: 1,
    dataType: DataType.uint,
    unit: Unit.packetId,
  },
  {
    byteId: 0x0b,
    byteLength: 3,
    varName: VarName.power,
    factor: 0.01,
    dataType: DataType.uint,
    unit: Unit.power,
  },
  {
    byteId: 0x5c,
    byteLength: 4,
    varName: VarName.power,
    factor: 0.01,
    dataType: DataType.sint,
    unit: Unit.power,
  },
  {
    byteId: 0x04,
    byteLength: 3,
    varName: VarName.pressure,
    factor: 0.01,
    dataType: DataType.uint,
    unit: Unit.pressure,
  },
  {
    byteId: 0x54,
    byteLength: 13,
    varName: VarName.raw,
    factor: 0.01,
    dataType: DataType.uint,
    unit: Unit.raw,
  },
  {
    byteId: 0x3f,
    byteLength: 2,
    varName: VarName.rotation,
    factor: 0.1,
    dataType: DataType.sint,
    unit: Unit.rotation,
  },
  {
    byteId: 0x44,
    byteLength: 2,
    varName: VarName.speed,
    factor: 0.01,
    dataType: DataType.uint,
    unit: Unit.speed,
  },
  {
    byteId: 0x57,
    byteLength: 1,
    varName: VarName.temperatureC,
    factor: 1,
    dataType: DataType.sint,
    unit: Unit.temperatureC,
    fixedPoint: 1,
  },
  {
    byteId: 0x58,
    byteLength: 1,
    varName: VarName.temperatureC,
    factor: 0.35,
    dataType: DataType.sint,
    unit: Unit.temperatureC,
    fixedPoint: 1,
  },
  {
    byteId: 0x45,
    byteLength: 2,
    varName: VarName.temperatureC,
    factor: 0.1,
    dataType: DataType.sint,
    unit: Unit.temperatureC,
    fixedPoint: 1,
  },
  {
    byteId: 0x02,
    byteLength: 2,
    varName: VarName.temperatureC,
    factor: 0.01,
    dataType: DataType.sint,
    unit: Unit.temperatureC,
    fixedPoint: 1,
  },
  {
    byteId: 0x53,
    byteLength: 10,
    varName: VarName.text,
    factor: 0.01,
    dataType: DataType.sint,
    unit: Unit.text,
  },
  {
    byteId: 0x50,
    byteLength: 4,
    varName: VarName.timeStamp,
    factor: 1,
    dataType: DataType.uint,
    unit: Unit.timeStamp,
  },
  {
    byteId: 0x13,
    byteLength: 2,
    varName: VarName.tvoc,
    factor: 1,
    dataType: DataType.uint,
    unit: Unit.tvoc,
  },
  {
    byteId: 0x0c,
    byteLength: 2,
    varName: VarName.voltage,
    factor: 0.001,
    dataType: DataType.uint,
    unit: Unit.voltage,
  },
  {
    byteId: 0x4a,
    byteLength: 2,
    varName: VarName.voltage,
    factor: 0.1,
    dataType: DataType.uint,
    unit: Unit.voltage,
  },
  {
    byteId: 0x4e,
    byteLength: 4,
    varName: VarName.volume,
    factor: 0.001,
    dataType: DataType.uint,
    unit: Unit.volume,
  },
  {
    byteId: 0x47,
    byteLength: 2,
    varName: VarName.volume,
    factor: 0.1,
    dataType: DataType.uint,
    unit: Unit.volume,
  },
  {
    byteId: 0x48,
    byteLength: 2,
    varName: VarName.volumeML,
    factor: 1,
    dataType: DataType.uint,
    unit: Unit.volumeML,
  },
  {
    byteId: 0x55,
    byteLength: 4,
    varName: VarName.volumeStorage,
    factor: 0.001,
    dataType: DataType.uint,
    unit: Unit.volumeStorage,
  },
  {
    byteId: 0x49,
    byteLength: 2,
    varName: VarName.volumeFlowRate,
    factor: 0.001,
    dataType: DataType.uint,
    unit: Unit.volumeFlowRate,
  },
  {
    byteId: 0x46,
    byteLength: 1,
    varName: VarName.uvIndex,
    factor: 1,
    dataType: DataType.uint,
    unit: Unit.uvIndex,
  },

  {
    byteId: 0x4f,
    byteLength: 4,
    varName: VarName.water,
    factor: 0.001,
    dataType: DataType.uint,
    unit: Unit.water,
  },
  {
    byteId: 0x5e,
    byteLength: 2,
    varName: VarName.direction,
    factor: 0.01,
    dataType: DataType.uint,
    unit: Unit.direction,
  },
  {
    byteId: 0x5f,
    byteLength: 2,
    varName: VarName.precipitation,
    factor: 1,
    dataType: DataType.uint,
    unit: Unit.precipitation,
  },
];
