export interface BTHomeData {
  type: VarName;
  value: number | string;
  unit?: Unit;
}

export interface BTHomePacket {
  version: string;
  data: BTHomeData[];
}

export interface BtHomeBytesType {
  byteId: number;
  byteLength: number;
  varName: VarName;
  factor: number;
  dataType: DataType;
  unit?: Unit;
}

export enum VarName {
  co2ppm = "CO2ppm",
  particulateMatter = "particulateMatter",
  particulateMatter10 = "particulateMatter10",
  relativeHumidity = "relativeHumidity",
  relativeHumidity2 = "relativeHumidity2",
  temperatureC = "temperatureC",
  temperatureC2 = "temperatureC2",
  tempCred = "tempCred",
  batteryLevel = "batteryLevel",
  count = "count",
  count2 = "count2",
  count3 = "count3",
  current = "current",
  dewpoint = "dewpoint",
  distanceMM = "distanceMM",
  distanceM = "distanceM",
  duration = "duration",
  energy = "energy",
  illuminance = "illuminance",
  massKG = "massKG",
  massLB = "massLB",
  moisture = "moisture",
  moisture2 = "moisture2",
  power = "power",
  pressure = "pressure",
  rotation = "rotation",
  speed = "speed",
  tvoc = "tvoc",
  voltage = "voltage",
  voltage2 = "voltage2",
  volumeL = "volumeL",
  volumeML = "volumeML",
  volumeFR = "volumeFR",
  UV = "UV",
  macAddress = "macAddress",
}

export enum DataType {
  uint = "uint",
  sint = "sint",
}

export enum Unit {
  co2ppm = "ppm",
  temperature = "°C",
  particulateMatter = "µg/m³",
  humidity = "%",
  batteryLevel = "%",
  current = "A",
  dewpoint = "°C",
  distanceM = "m",
  distanceMM = "mm",
  duration = "s",
  energy = "kWh",
  illuminance = "lux",
  massKG = "kg",
  massLB = "lb",
  moisture = "%",
  power = "w",
  pressure = "hpa",
  rotation = "°",
  speed = "m/s",
  tvoc = "µg/m³",
  voltage = "v",
  volumeL = "L",
  volumeML = "mL",
  volumeFR = "m³/hr",
  macAddress = "",
}

export const btHomeBytes: BtHomeBytesType[] = [
  {
    byteId: 1,
    byteLength: 1,
    varName: VarName.batteryLevel,
    factor: 1,
    dataType: DataType.uint,
    unit: Unit.batteryLevel,
  },
  {
    byteId: 2,
    byteLength: 2,
    varName: VarName.temperatureC,
    factor: 0.01,
    dataType: DataType.sint,
    unit: Unit.temperature,
  },
  {
    byteId: 3,
    byteLength: 2,
    varName: VarName.relativeHumidity,
    factor: 0.01,
    dataType: DataType.uint,
    unit: Unit.humidity,
  },
  {
    byteId: 4,
    byteLength: 3,
    varName: VarName.pressure,
    factor: 0.01,
    dataType: DataType.uint,
    unit: Unit.pressure,
  },
  {
    byteId: 5,
    byteLength: 3,
    varName: VarName.illuminance,
    factor: 0.01,
    dataType: DataType.uint,
    unit: Unit.illuminance,
  },
  {
    byteId: 6,
    byteLength: 2,
    varName: VarName.massKG,
    factor: 0.01,
    dataType: DataType.uint,
    unit: Unit.massKG,
  },
  {
    byteId: 7,
    byteLength: 2,
    varName: VarName.massLB,
    factor: 0.01,
    dataType: DataType.uint,
    unit: Unit.illuminance,
  },
  {
    byteId: 8,
    byteLength: 2,
    varName: VarName.dewpoint,
    factor: 0.01,
    dataType: DataType.sint,
    unit: Unit.dewpoint,
  },
  {
    byteId: 9,
    byteLength: 1,
    varName: VarName.count,
    factor: 1,
    dataType: DataType.uint,
  },
  {
    byteId: 10,
    byteLength: 3,
    varName: VarName.energy,
    factor: 0.001,
    dataType: DataType.uint,
    unit: Unit.energy,
  },
  {
    byteId: 11,
    byteLength: 3,
    varName: VarName.power,
    factor: 0.01,
    dataType: DataType.uint,
    unit: Unit.power,
  },
  {
    byteId: 12,
    byteLength: 2,
    varName: VarName.voltage,
    factor: 0.001,
    dataType: DataType.uint,
    unit: Unit.voltage,
  },
  {
    byteId: 13,
    byteLength: 2,
    varName: VarName.particulateMatter,
    factor: 1,
    dataType: DataType.uint,
    unit: Unit.particulateMatter,
  },
  {
    byteId: 14,
    byteLength: 2,
    varName: VarName.particulateMatter10,
    factor: 1,
    dataType: DataType.uint,
    unit: Unit.particulateMatter,
  },
  {
    byteId: 18,
    byteLength: 2,
    varName: VarName.co2ppm,
    factor: 1,
    dataType: DataType.uint,
    unit: Unit.co2ppm,
  },
  {
    byteId: 19,
    byteLength: 2,
    varName: VarName.tvoc,
    factor: 1,
    dataType: DataType.uint,
    unit: Unit.tvoc,
  },
  {
    byteId: 20,
    byteLength: 2,
    varName: VarName.moisture,
    factor: 0.01,
    dataType: DataType.uint,
    unit: Unit.moisture,
  },

  {
    byteId: 46,
    byteLength: 1,
    varName: VarName.relativeHumidity2,
    factor: 1,
    dataType: DataType.uint,
    unit: Unit.humidity,
  },

  {
    byteId: 47,
    byteLength: 1,
    varName: VarName.moisture2,
    factor: 1,
    dataType: DataType.uint,
    unit: Unit.moisture,
  },
  {
    byteId: 61,
    byteLength: 2,
    varName: VarName.count2,
    factor: 1,
    dataType: DataType.uint,
  },
  {
    byteId: 62,
    byteLength: 4,
    varName: VarName.count3,
    factor: 1,
    dataType: DataType.uint,
  },
  {
    byteId: 63,
    byteLength: 2,
    varName: VarName.rotation,
    factor: 0.1,
    dataType: DataType.sint,
    unit: Unit.rotation,
  },
  {
    byteId: 64,
    byteLength: 2,
    varName: VarName.distanceMM,
    factor: 1,
    dataType: DataType.uint,
    unit: Unit.distanceMM,
  },

  {
    byteId: 65,
    byteLength: 2,
    varName: VarName.distanceM,
    factor: 0.1,
    dataType: DataType.uint,
    unit: Unit.distanceM,
  },
  {
    byteId: 66,
    byteLength: 3,
    varName: VarName.duration,
    factor: 0.001,
    dataType: DataType.uint,
    unit: Unit.duration,
  },
  {
    byteId: 67,
    byteLength: 2,
    varName: VarName.current,
    factor: 0.001,
    dataType: DataType.uint,
    unit: Unit.current,
  },
  {
    byteId: 68,
    byteLength: 2,
    varName: VarName.speed,
    factor: 0.01,
    dataType: DataType.uint,
    unit: Unit.speed,
  },

  {
    byteId: 69,
    byteLength: 2,
    varName: VarName.temperatureC2,
    factor: 0.1,
    dataType: DataType.sint,
    unit: Unit.temperature,
  },
  {
    byteId: 70,
    byteLength: 1,
    varName: VarName.UV,
    factor: 1,
    dataType: DataType.uint,
  },
  {
    byteId: 71,
    byteLength: 2,
    varName: VarName.volumeL,
    factor: 0.1,
    dataType: DataType.uint,
    unit: Unit.volumeL,
  },
  {
    byteId: 72,
    byteLength: 2,
    varName: VarName.volumeML,
    factor: 1,
    dataType: DataType.uint,
    unit: Unit.volumeML,
  },
  {
    byteId: 73,
    byteLength: 2,
    varName: VarName.volumeFR,
    factor: 0.001,
    dataType: DataType.uint,
    unit: Unit.volumeFR,
  },
  {
    byteId: 74,
    byteLength: 2,
    varName: VarName.voltage2,
    factor: 0.1,
    dataType: DataType.uint,
    unit: Unit.voltage,
  },
];
